version: '3.8'
services:
  app:
    build: 
      context: .
      dockerfile: Dockerfile
    environment:
      DATABASE_URL: postgres://admin:admin123@postgres:5432/solana_indexer
      VALIDATOR_PUB_KEY: ${VALIDATOR_PUB_KEY}
      VALIDATOR_ID: ${VALIDATOR_ID}
      START_EPOCH: ${START_EPOCH}
    depends_on:
      - postgres
    volumes:
      - .:/app
      - /app/node_modules
    command: ["bun", "run", "dev"]

  postgres:
    image: postgres:16
    container_name: solana-indexer-postgres
    restart: always
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: solana_indexer
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:

